input {
  jdbc {
    jdbc_driver_class => "com.microsoft.sqlserver.jdbc.SQLServerDriver"
    jdbc_connection_string => "jdbc:sqlserver://host.docker.internal:1433;databaseName=Medicine;encrypt=false;"
    jdbc_user => "sa"
    jdbc_password => "123456"
    statement => "SELECT * FROM mediclist"
    schedule => "* * * * *"
  }
}

filter {
 
}

output {
  elasticsearch {
    hosts => ["http://host.docker.internal:9200"]
    index => "mediclist"                
    document_id => "%{sku}"             
  }
  

  stdout { 
    codec => rubydebug 
  }
}